/**
 * 
 */
package com.itmill.incubator.stylecalendar.client;

import com.itmill.incubator.stylecalendar.client.ui.VStyleCalendar;
import com.vaadin.terminal.gwt.client.DefaultWidgetSet;
import com.vaadin.terminal.gwt.client.Paintable;
import com.vaadin.terminal.gwt.client.UIDL;

/**
 * @author Risto Yrjänä / IT Mill Ltd.
 *
 */
public class StyleCalendarWidgetset extends DefaultWidgetSet {

    /** Creates a widget according to its class name. */
    public Paintable createWidget(UIDL uidl) {
        final Class<?> classType = resolveWidgetType(uidl);

        Paintable p = createWidgetByClass(classType);
        if (p == null) {
            // Let the DefaultWidgetSet handle creation of default widgets
            p = super.createWidget(uidl);
        }

        return p;
    }

    /** Resolves UIDL tag name to class . */
    protected Class<?> resolveWidgetType(UIDL uidl) {
        final String tag = uidl.getTag();

        Class<?> c = resolveWidgetByTag(tag);

        if (c == null) {
            c = super.resolveWidgetType(uidl);
        }

        // Let the DefaultWidgetSet handle resolution of default widgets
        return c;
    }

    // This method gets AUTOGENERATED by Vaadin plugin
    private Paintable createWidgetByClass(Class<?> classType) {
        if (classType == VStyleCalendar.class) {
            return new VStyleCalendar();
        } else {
            return null;
        }
    }

    // This method gets AUTOGENERATED by Vaadin plugin
    private Class<?> resolveWidgetByTag(final String tag) {
        if (VStyleCalendar.TAGNAME.equals(tag)) {
            return VStyleCalendar.class;
        } else {
            return null;
        }
    }

}
